name: Buttons
options:
  bundleIdPrefix: gg.pekk.buttons
  deploymentTarget:
    iOS: "17.0"
targets:
  Buttons:
    type: application
    platform: iOS
    sources:
      - Buttons
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: gg.pekk.buttons
        CODE_SIGN_STYLE: Automatic
        DEVELOPMENT_TEAM: 6URP555BR7
        TARGETED_DEVICE_FAMILY: "1"
    info:
      path: Generated-Info.plist
      properties:
        UILaunchScreen: {}
